---
author: "Mauricio Nickel"
email: "duktus@duck.com"
lang: en
title: "CV"
gitlab: "https://gitlab.com/duktus"
interests:
  - Digital Humanities
  - Data Journalism
  - Design and Webdesign
  - Figurational Sociology
  - Political Philosophy
  - Sociology of Space
  - Sociology of Time
  - History of Ideas
  - GNU/Linux
  - Football
---

